<?php

return [
    [
        "id" => 1,
        "user_id" => 1,
        "title" => "Cob Cottage",
        "description" => "Soddisfa il bisogno di una pausa in questa casa costruita sulla terra, unica nel suo genere. L'accogliente rifugio è stato scolpito a mano utilizzando materiali naturali locali e sostenibili e dispone di uno spazio abitativo centrale con scale a sbalzo che conducono alla camera da letto mansardata.",
        "street" => "436-498 N Cedar St, Coquille, OR 97423, Stati Uniti",
        "longitude" => 43.178174,
        "latitude" => -124.192441,
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "size" => 60,
        "visibility" => true,
        "cover" => "../storage/img/a6.webp",
    ],
    [
        "id" => 2,
        "user_id" => 1,
        "title" => "AirShip",
        "description" => "Rifugiati sulla terrazza di questa vacanza sostenibile e ammira le scintillanti costellazioni sotto un'accogliente coperta di tartan. AirShip 2 è un iconico chalet in alluminio isolato progettato da Roderick James con vista sul Sound of Mull dalle finestre delle dragonfly. Airship002 è comodo, eccentrico e alla moda. Non finge di essere un hotel a cinque stelle. Le recensioni raccontano la storia. Se hai prenotato le date, dai un'occhiata al nostro nuovo annuncio The Pilot House, Drimnin, che si trova sullo stesso sito di 4 acra.",
        "street" => "1 Shore St, Oban PA34 4LJ, Regno Unito",
        "longitude" => 56.411952404191894,
        "latitude" => -5.473317745356685,
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "size" => 45,
        "visibility" => true,
        "cover" => "../storage/img/b1.webp",
    ],
    [
        "id" => 3,
        "user_id" => 2,
        "title" => "Igloo da neve",
        "description" => "Igloo da neve con letti veri all'interno. Bella atmosfera con luci a led e pareti bianche. Fuori dall'igloo è possibile vedere l'aurora boreale se siete fortunati. Vieni in Lapponia ed esplora la natura selvaggia.",
        "street" => "Riekontie 8, 99400 Enontekiö, Finlandia",
        "longitude" => 68.38699978743816,
        "latitude" => 23.640721040396283,
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "size" => 30,
        "visibility" => true,
        "cover" => "../storage/img/c1.webp",
    ],
    [
        "id" => 4,
        "user_id" => 2,
        "title" => "Casa Acantilado",
        "description" => "Considerata un'icona architettonica della Costa de Granada. Si tratta di una casa unica costruita all'interno della montagna,che offre una temperatura costante di 20 gradi durante tutto l'anno. È un design e arredi esclusivi, il tetto ondulato e la spaziosa cucina integrata nel grande salotto di 150 metri quadrati con vista sul Mar Mediterraneo lascerà chiunque senza fiato. La spiaggia dista 5 km per gli appassionati di sport acquatici e, se preferisci le attività invernali,puoi praticare lo sci in Sierra Nevada",
        "street" => "Av. Mar de Melicena, 84, 18713 Melicena, Granada, Spagna",
        "longitude" => 36.75121067197024,
        "latitude" => -3.2351454037841703,
        "rooms" => 6,
        "beds" => 4,
        "bathrooms" => 3,
        "size" => 400,
        "visibility" => true,
        "cover" => "../storage/img/d1.webp",
    ],
    [
        "id" => 5,
        "user_id" => 2,
        "title" => "Mirror House North",
        "description" => "Le Mirror Houses sono una coppia di case vacanza, situate nella meravigliosa cornice delle Dolomiti altoatesine, in uno splendido scenario di meli, appena fuori dalla città di Bolzano.Le case a specchio offrono un'occasione unica per trascorrere una bella vacanza circondati da architettura contemporanea di altissimo livello e il paesaggio più sorprendente e la bellezza della natura ha da offrire.",
        "street" => "Grutzenweg, 75, 39100 Bozen, Autonome Provinz Bozen - Südtirol",
        "longitude" => 46.46236614796121,
        "latitude" => 11.312698993455259,
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "size" => 65,
        "visibility" => true,
        "cover" => "../storage/img/e1.webp",
    ],
    [
        "id" => 6,
        "user_id" => 2,
        "title" => "Casa la Terre",
        "description" => "Vi diamo il benvenuto ai margini della foresta in una casa in legno eco-responsabile, con spa, WiFi e aria condizionata reversibile, per soggiorni in coppia o in famiglia nel cuore del Périgord. Immersi nel cuore del vallone, sarete soli al mondo per momenti magici e degusterete questo avrete scelto tra la nostra gamma di prodotti locali (premiati al Concorso Agricolo) - eventualmente dopo aver approfittato dei massaggi di Cécile.",
        "street" => "Via Castel Sant'Elia, 01033 Civita Castellana VT",
        "longitude" => 42.28456517120516,
        "latitude" => 12.41798063771513,
        "rooms" => 3,
        "beds" => 4,
        "bathrooms" => 1,
        "size" => 70,
        "visibility" => true,
        "cover" => "../storage/img/f1.webp",
    ],
    [
        "id" => 7,
        "user_id" => 3,
        "title" => "Mi Chalet",
        "description" => "Chalet di lusso in Alta Badia per la vostra fuga romantica.Il Mi Chalet è stato progettato dal pioniere dell'architettura in legno, l’architetto Karl Heinz Castlunger, con in mente sostenibilità, calore e bellezza.Immerso nella spettacolare catena montuosa delle Dolomiti, nella valle dell'Alta Badia, questo patrimonio mondiale dell'Unesco è una rinomata località sciistica in inverno e un'area escursionistica mozzafiato in estate.",
        "street" => "Via Cavour, 13, 00040 Rocca di Papa RM",
        "longitude" => 41.76164637008114,
        "latitude" => 12.706215431946408,
        "rooms" => 3,
        "beds" => 1,
        "bathrooms" => 1,
        "size" => 67,
        "visibility" => true,
        "cover" => "../storage/img/g1.webp",
    ],
    [
        "id" => 8,
        "user_id" => 3,
        "title" => "Nell'UFO47",
        "description" => "Design eccezionale. Unico. Ecologico, sostenibile, accogliente e costruito in legno, vetro e metallo locali: una vera casa in legno del falegname! Sorseggia un sole caldo o un'ombra fresca su uno dei tre balconi, rilassati nella sauna in giardino che si affaccia sull'esterno, tuffati nell'umido rinfrescante del laghetto, osserva il caminetto scoppiettante.",
        "street" => "Köslau 3, 97486 Königsberg in Bayern, Germania",
        "longitude" => 50.06085498883344,
        "latitude" => 10.672373765765292,
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "size" => 67,
        "visibility" => true,
        "cover" => "../storage/img/h1.webp",
    ],
    [
        "id" => 9,
        "user_id" => 3,
        "title" => "Unica Villa sul lungomare",
        "description" => "Splendida casa disegnata dall’architetto Clemente Busiri Vici. Due box auto più piazzale per altre due auto. Discesa per persone disabili altrimenti scale in roccia per scendere giù alla casa. 2 camere da letto grandi con bagno en suite, due più piccole con un bagno. Cabina per gli ospiti con doccia. Salone, sala da pranzo, esterno con due saloni, patio con grande tavolo da pranzo da 12 posti.",
        "street" => "Via Giovanni Paisiello, 41 00198 Roma, Italia",
        "longitude" => 41.919221254434916,
        "latitude" => 12.49278411438564,
        "rooms" => 12,
        "beds" => 6,
        "bathrooms" => 5,
        "size" => 400,
        "visibility" => true,
        "cover" => "../storage/img/i1.webp",
    ],
    [
        "id" => 10,
        "user_id" => 2,
        "title" => "Dom'Up of Hodoumont",
        "description" => "Il Dom'Up di Hodoumont - vieni a trovarti in alto, con la vista su uno dei più bei castelli della Vallonia in mezzo alla natura - un'esperienza unica.Scopri il campeggio glamour nella splendida regione di Condroz per esporti alle risorse e alla natura, con la colazione consegnata sotto la tenda ogni mattina!",
        "street" => "Rue de Hodoumont 1, 5354 Ohey, Belgio",
        "longitude" => 50.436553896749984,
        "latitude" => 5.198986062037705,
        "rooms" => 1,
        "beds" => 2,
        "bathrooms" => 1,
        "size" => 30,
        "visibility" => true,
        "cover" => "../storage/img/l1.webp",
    ],
    [
        "id" => 11,
        "user_id" => 1,
        "title" => "IL LOFT DELLA FABBRICA",
        "description" => "Invita questo magnifico loft di 700 m ² vicino alla tranquilla foresta e lontano dalla vista... Per il design e l'aspetto industriale, si adatterà alla tua famiglia, ai soggiorni professionali e ai tuoi eventi. Non ne resterai deluso!",
        "street" => "9 Rue de Joseph, 91680 Bruyères-le-Châtel, Francia",
        "longitude" => 48.59514957244395,
        "latitude" => 2.1930511772809624,
        "rooms" => 11,
        "beds" => 5,
        "bathrooms" => 5,
        "size" => 395,
        "visibility" => true,
        "cover" => "../storage/img/m1.webp",
    ],
    [
        "id" => 12,
        "user_id" => 1,
        "title" => "Casa dell'artista",
        "description" => "Magica casa vacanze e studio di design nel cuore della Puglia.Trullonostrano è il riflesso del nostro lavoro artistico, restaurato con amore e rispetto per l'architettura tradizionale. Ci piacerebbe condividere il nostro stile di vita e aprire la porta e l'anima della nostra casa per un'esperienza unica nella magica terra pugliese.",
        "street" => "Via Allievo Ufficiale Francesco Saverio Mastropierro, 3, 70056 Molfetta BA",
        "longitude" => 41.20116941731249,
        "latitude" => 16.607682391239102,
        "rooms" => 7,
        "beds" => 4,
        "bathrooms" => 2,
        "size" => 178,
        "visibility" => true,
        "cover" => "../storage/img/n1.webp",
    ],
    [
        "id" => 13,
        "user_id" => 1,
        "title" => "Villa Mediterraneo 2",
        "description" => "Villa Mediterraneo 2, nuova villa di lusso, completata nel 2021, classificata con 5 *. La chiara visione del proprietario e l'esperienza di viaggiare in tutto il mondo hanno portato alla realizzazione della proprietà. Alcune soluzioni architettoniche sono ispirate all'edificio Grande Arche del quartiere La Defense (FR).",
        "street" => "Contrada Trappeto, Borghetto San Nicola, Frazione Cariglio, 87024 Fuscaldo CS",
        "longitude" => 39.42790417953122,
        "latitude" => 16.009828857531275,
        "rooms" => 10,
        "beds" => 4,
        "bathrooms" => 4,
        "size" => 238,
        "visibility" => true,
        "cover" => "../storage/img/o1.webp",
    ],
    [
        "id" => 14,
        "user_id" => 2,
        "title" => "Il vecchio mulino",
        "description" => "Vecchio mulino (olio di noci) restaurato combinando il moderno con il fascino della pietra.Questa abitazione di 27m2 si trova nelle alture di Chinon, non lontano dalla fortezza reale. Situato a 1,3 km dal centro della città (25 minuti a piedi, possibilità di prendere un ascensore gratuito)",
        "street" => "Via Giorgio Rizzo, 126, 98057 Milazzo ME",
        "longitude" => 38.216074979251836,
        "latitude" => 15.240210996436726,
        "rooms" => 3,
        "beds" => 1,
        "bathrooms" => 1,
        "size" => 42,
        "visibility" => true,
        "cover" => "../storage/img/p1.webp",
    ],
    [
        "id" => 15,
        "user_id" => 1,
        "title" => "Fienile di lusso",
        "description" => "Benvenuti al Coeur De La Vallée, Cuore della Valle. La nostra GÎte si trova in una posizione da cartolina, immersa in una splendida valle nel nord-est della Normandia, dove è possibile rilassarsi e godersi la campagna francese. Coeur De La Vallée è davvero il luogo ideale per le vostre vacanze, che si tratti di un'avventura in famiglia o di una fuga di coppia abbiamo tutto da offrire. Si prega di visitare il nostro nuovo sito per tutti i dettagli e per prenotare le proprietà direttamente.",
        "street" => "Via Vittorio Emanuele, 70, 98030 Floresta ME",
        "longitude" => 37.98684667239117,
        "latitude" => 14.909820405721051,
        "rooms" => 8,
        "beds" => 4,
        "bathrooms" => 2,
        "size" => 165,
        "visibility" => true,
        "cover" => "../storage/img/q1.webp",
    ],
    [
        "id" => 16,
        "user_id" => 3,
        "title" => "Chalet in stile loft",
        "description" => "Chalet in stile mini loft indipendente. Annesso nuovo dell'abitazione principale , questo alloggio di 40 m² è costituito da una parte soggiorno( divano letto 140) , un angolo cottura attrezzato ( frigorifero, forno, piastre a induzione, forno a microonde), una parte camera da letto e un angolo sanitario. Alloggio davvero indipendente con attrezzatura completa. Aria condizionata, terrazza, parcheggio auto.",
        "street" => "Via S. Marco, 40, 95011 Calatabiano CT",
        "longitude" => 37.802069420492536,
        "latitude" => 15.24745889643108,
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "size" => 68,
        "visibility" => true,
        "cover" => "../storage/img/r1.webp",
    ],
    [
        "id" => 17,
        "user_id" => 3,
        "title" => "Birdbox",
        "description" => "Goditi il recinto rilassato e confortevole della Birdbox. Dormire proprio accanto alla natura e ai suoi incredibili dintorni. Sdraiati e ammira le spettacolari montagne che ti circondano. Indossate gli sci e fate un viaggio mozzafiato lungo i sentieri vicini. Escursione giù a Langelandsvatnet in estate e godere di nuoto in acqua energizzante. La tua immaginazione è il limite di ciò che puoi sperimentare.",
        "street" => "6815 Bjørkedal, Norvegia",
        "longitude" => 61.460055879088735,
        "latitude" => 5.65235978863308,
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "size" => 39,
        "visibility" => true,
        "cover" => "../storage/img/s1.webp",
    ],
    [
        "id" => 18,
        "user_id" => 1,
        "title" => "Alianz Loft",
        "description" => "20 minuti dall'aeroporto di San Jose. Primo loft costruito da Alianz. Esso contiene una terrazza coperta, jacuzzi, focolare, giardino conigli, due camere, due balconi, cancello d'ingresso, giardino privato, parcheggio privato, zona barbecue, aria condizionata in ogni camera da letto, campo da basket, letti di lusso e vista sulle montagne. Ideale per gli amanti dell'architettura, appuntamenti romantici o per divertirsi. È uno spazio unico del suo genere.",
        "street" => "2V76+3XH, Heredia Province, San Roque, Costa Rica",
        "longitude" => 10.012704520877664,
        "latitude" => -84.13750929763751,
        "rooms" => 7,
        "beds" => 2,
        "bathrooms" => 2,
        "size" => 120,
        "visibility" => true,
        "cover" => "../storage/img/t1.webp",
    ],
    [
        "id" => 19,
        "user_id" => 3,
        "title" => "The Bloomhouse",
        "description" => "Hai mai soggiornato in un enorme unicorno di mare? No, non l'hai fatto, ma ora puoi barrarla dalla tua lista dei desideri. Questa magica opera d'arte fa parte di Willy Wonka, in parte Big Lebowski, e totalmente diversa da qualsiasi altra parte. Fallo per il grammo, ma anche per la tua anima.",
        "street" => "4302 Airport Blvd, Austin, TX 78722, Stati Uniti",
        "longitude" => 30.29821624284684,
        "latitude" => -97.71003995078038,
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "size" => 53,
        "visibility" => true,
        "cover" => "../storage/img/u1.webp",
    ],
    [
        "id" => 20,
        "user_id" => 2,
        "title" => "Quetzalcoatl",
        "description" => "Quetzalcoatl Nest è un complesso residenziale privato costruito dall'architetto Javier Senosiain, in cui segue gli aspetti dell'architettura organica, cercando di creare spazi più umani.",
        "street" => "Washington 503-C, Zona Centro, 87300 Heroica Matamoros, Tamps., Messico",
        "longitude" => 25.87529191473353,
        "latitude" => -97.4996680165004,
        "rooms" => 9,
        "beds" => 4,
        "bathrooms" => 4,
        "size" => 215,
        "visibility" => true,
        "cover" => "../storage/img/v1.webp",
    ],
    [
        "id" => 21,
        "user_id" => 2,
        "title" => "Guitar House",
        "description" => "La nostra Guitar House è stata progettata per offrirti non solo un alloggio, ma anche un'esperienza completamente unica. Soggiornare nel nostro alloggio ti darà la sensazione di una minicasa, la vista di uno chalet di montagna, il comfort e lo spazio di un bungalow con acqua calda, riscaldamento, wifi ed elettricità. Qui sarai sulla griglia, ma fuori dal pavimento",
        "street" => "273-3 Tokiwa, Kamakura, Kanagawa 248-0022, Giappone",
        "longitude" => 35.32836597784234,
        "latitude" => 139.5230704995829,
        "rooms" => 5,
        "beds" => 2,
        "bathrooms" => 1,
        "size" => 71,
        "visibility" => true,
        "cover" => "../storage/img/z1.webp",
    ],
    //     [
    //         "id" => 2,
    //         "user_id" => 1,
    //         "title" => "AirShip",
    //         "street" => null,
    //         "description" => "Rifugiati sulla terrazza di questa vacanza sostenibile e ammira le scintillanti costellazioni sotto un'accogliente coperta di tartan. AirShip 2 è un iconico chalet in alluminio isolato progettato da Roderick James con vista sul Sound of Mull dalle finestre delle dragonfly. Airship002 è comodo, eccentrico e alla moda. Non finge di essere un hotel a cinque stelle. Le recensioni raccontano la storia. Se hai prenotato le date, dai un'occhiata al nostro nuovo annuncio The Pilot House, Drimnin, che si trova sullo stesso sito di 4 acra.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 2,
    //         "beds" => 1,
    //         "bathrooms" => 1,
    //         "size" => 45,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 3,
    //         "user_id" => 2,
    //         "title" => "Igloo da neve",
    //         "street" => null,
    //         "description" => "Igloo da neve con letti veri all'interno. Bella atmosfera con luci a led e pareti bianche. Fuori dall'igloo è possibile vedere l'aurora boreale se siete fortunati. Vieni in Lapponia ed esplora la natura selvaggia.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 1,
    //         "beds" => 1,
    //         "bathrooms" => 1,
    //         "size" => 30,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 4,
    //         "user_id" => 2,
    //         "title" => "Casa Acantilado",
    //         "street" => null,
    //         "description" => "Considerata un'icona architettonica della Costa de Granada. Si tratta di una casa unica costruita all'interno della montagna,che offre una temperatura costante di 20 gradi durante tutto l'anno. È un design e arredi esclusivi, il tetto ondulato e la spaziosa cucina integrata nel grande salotto di 150 metri quadrati con vista sul Mar Mediterraneo lascerà chiunque senza fiato. La spiaggia dista 5 km per gli appassionati di sport acquatici e, se preferisci le attività invernali,puoi praticare lo sci in Sierra Nevada",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 6,
    //         "beds" => 4,
    //         "bathrooms" => 3,
    //         "size" => 400,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 5,
    //         "user_id" => 2,
    //         "title" => "Mirror House North",
    //         "street" => null,
    //         "description" => "Le Mirror Houses sono una coppia di case vacanza, situate nella meravigliosa cornice delle Dolomiti altoatesine, in uno splendido scenario di meli, appena fuori dalla città di Bolzano.Le case a specchio offrono un'occasione unica per trascorrere una bella vacanza circondati da architettura contemporanea di altissimo livello e il paesaggio più sorprendente e la bellezza della natura ha da offrire.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 2,
    //         "beds" => 1,
    //         "bathrooms" => 1,
    //         "size" => 65,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 6,
    //         "user_id" => 2,
    //         "title" => "Casa la Terre",
    //         "street" => null,
    //         "description" => "Vi diamo il benvenuto ai margini della foresta in una casa in legno eco-responsabile, con spa, WiFi e aria condizionata reversibile, per soggiorni in coppia o in famiglia nel cuore del Périgord. Immersi nel cuore del vallone, sarete soli al mondo per momenti magici e degusterete questo avrete scelto tra la nostra gamma di prodotti locali (premiati al Concorso Agricolo) - eventualmente dopo aver approfittato dei massaggi di Cécile.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 3,
    //         "beds" => 4,
    //         "bathrooms" => 1,
    //         "size" => 70,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 7,
    //         "user_id" => 3,
    //         "title" => "Mi Chalet",
    //         "street" => null,
    //         "description" => "Chalet di lusso in Alta Badia per la vostra fuga romantica.Il Mi Chalet è stato progettato dal pioniere dell'architettura in legno, l’architetto Karl Heinz Castlunger, con in mente sostenibilità, calore e bellezza.Immerso nella spettacolare catena montuosa delle Dolomiti, nella valle dell'Alta Badia, questo patrimonio mondiale dell'Unesco è una rinomata località sciistica in inverno e un'area escursionistica mozzafiato in estate.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 3,
    //         "beds" => 1,
    //         "bathrooms" => 1,
    //         "size" => 67,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 8,
    //         "user_id" => 3,
    //         "title" => "Nell'UFO47",
    //         "street" => null,
    //         "description" => "Design eccezionale. Unico. Ecologico, sostenibile, accogliente e costruito in legno, vetro e metallo locali: una vera casa in legno del falegname! Sorseggia un sole caldo o un'ombra fresca su uno dei tre balconi, rilassati nella sauna in giardino che si affaccia sull'esterno, tuffati nell'umido rinfrescante del laghetto, osserva il caminetto scoppiettante.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 3,
    //         "beds" => 2,
    //         "bathrooms" => 1,
    //         "size" => 67,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 9,
    //         "user_id" => 3,
    //         "title" => "Unica Villa sul lungomare",
    //         "street" => null,
    //         "description" => "Splendida casa disegnata dall’architetto Clemente Busiri Vici. Due box auto più piazzale per altre due auto. Discesa per persone disabili altrimenti scale in roccia per scendere giù alla casa. 2 camere da letto grandi con bagno en suite, due più piccole con un bagno. Cabina per gli ospiti con doccia. Salone, sala da pranzo, esterno con due saloni, patio con grande tavolo da pranzo da 12 posti.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 12,
    //         "beds" => 6,
    //         "bathrooms" => 5,
    //         "size" => 400,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 10,
    //         "user_id" => 2,
    //         "title" => "Dom'Up of Hodoumont",
    //         "street" => null,
    //         "description" => "Il Dom'Up di Hodoumont - vieni a trovarti in alto, con la vista su uno dei più bei castelli della Vallonia in mezzo alla natura - un'esperienza unica.Scopri il campeggio glamour nella splendida regione di Condroz per esporti alle risorse e alla natura, con la colazione consegnata sotto la tenda ogni mattina!",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 1,
    //         "beds" => 2,
    //         "bathrooms" => 1,
    //         "size" => 30,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 11,
    //         "user_id" => 1,
    //         "title" => "IL LOFT DELLA FABBRICA",
    //         "street" => null,
    //         "description" => "Invita questo magnifico loft di 700 m ² vicino alla tranquilla foresta e lontano dalla vista... Per il design e l'aspetto industriale, si adatterà alla tua famiglia, ai soggiorni professionali e ai tuoi eventi. Non ne resterai deluso!",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 11,
    //         "beds" => 5,
    //         "bathrooms" => 5,
    //         "size" => 395,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 12,
    //         "user_id" => 1,
    //         "title" => "Casa dell'artista",
    //         "street" => null,
    //         "description" => "Magica casa vacanze e studio di design nel cuore della Puglia.Trullonostrano è il riflesso del nostro lavoro artistico, restaurato con amore e rispetto per l'architettura tradizionale. Ci piacerebbe condividere il nostro stile di vita e aprire la porta e l'anima della nostra casa per un'esperienza unica nella magica terra pugliese.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 7,
    //         "beds" => 4,
    //         "bathrooms" => 2,
    //         "size" => 178,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 13,
    //         "user_id" => 1,
    //         "title" => "Villa Mediterraneo 2",
    //         "street" => null,
    //         "description" => "Villa Mediterraneo 2, nuova villa di lusso, completata nel 2021, classificata con 5 *. La chiara visione del proprietario e l'esperienza di viaggiare in tutto il mondo hanno portato alla realizzazione della proprietà. Alcune soluzioni architettoniche sono ispirate all'edificio Grande Arche del quartiere La Defense (FR).",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 10,
    //         "beds" => 4,
    //         "bathrooms" => 4,
    //         "size" => 238,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 14,
    //         "user_id" => 2,
    //         "title" => "Il vecchio mulino",
    //         "street" => null,
    //         "description" => "Vecchio mulino (olio di noci) restaurato combinando il moderno con il fascino della pietra.Questa abitazione di 27m2 si trova nelle alture di Chinon, non lontano dalla fortezza reale. Situato a 1,3 km dal centro della città (25 minuti a piedi, possibilità di prendere un ascensore gratuito)",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 3,
    //         "beds" => 1,
    //         "bathrooms" => 1,
    //         "size" => 42,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 15,
    //         "user_id" => 1,
    //         "title" => "Fienile di lusso",
    //         "street" => null,
    //         "description" => "Benvenuti al Coeur De La Vallée, Cuore della Valle. La nostra GÎte si trova in una posizione da cartolina, immersa in una splendida valle nel nord-est della Normandia, dove è possibile rilassarsi e godersi la campagna francese. Coeur De La Vallée è davvero il luogo ideale per le vostre vacanze, che si tratti di un'avventura in famiglia o di una fuga di coppia abbiamo tutto da offrire. Si prega di visitare il nostro nuovo sito per tutti i dettagli e per prenotare le proprietà direttamente.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 8,
    //         "beds" => 4,
    //         "bathrooms" => 2,
    //         "size" => 165,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 16,
    //         "user_id" => 3,
    //         "title" => "Chalet in stile loft",
    //         "street" => null,
    //         "description" => "Chalet in stile mini loft indipendente. Annesso nuovo dell'abitazione principale , questo alloggio di 40 m² è costituito da una parte soggiorno( divano letto 140) , un angolo cottura attrezzato ( frigorifero, forno, piastre a induzione, forno a microonde), una parte camera da letto e un angolo sanitario. Alloggio davvero indipendente con attrezzatura completa. Aria condizionata, terrazza, parcheggio auto.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 3,
    //         "beds" => 2,
    //         "bathrooms" => 1,
    //         "size" => 68,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 17,
    //         "user_id" => 3,
    //         "title" => "Birdbox",
    //         "street" => null,
    //         "description" => "Goditi il recinto rilassato e confortevole della Birdbox. Dormire proprio accanto alla natura e ai suoi incredibili dintorni. Sdraiati e ammira le spettacolari montagne che ti circondano. Indossate gli sci e fate un viaggio mozzafiato lungo i sentieri vicini. Escursione giù a Langelandsvatnet in estate e godere di nuoto in acqua energizzante. La tua immaginazione è il limite di ciò che puoi sperimentare.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 1,
    //         "beds" => 1,
    //         "bathrooms" => 1,
    //         "size" => 39,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 18,
    //         "user_id" => 1,
    //         "title" => "Alianz Loft",
    //         "street" => null,
    //         "description" => "20 minuti dall'aeroporto di San Jose. Primo loft costruito da Alianz. Esso contiene una terrazza coperta, jacuzzi, focolare, giardino conigli, due camere, due balconi, cancello d'ingresso, giardino privato, parcheggio privato, zona barbecue, aria condizionata in ogni camera da letto, campo da basket, letti di lusso e vista sulle montagne. Ideale per gli amanti dell'architettura, appuntamenti romantici o per divertirsi. È uno spazio unico del suo genere.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 7,
    //         "beds" => 2,
    //         "bathrooms" => 2,
    //         "size" => 120,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 19,
    //         "user_id" => 3,
    //         "title" => "The Bloomhouse",
    //         "street" => null,
    //         "description" => "Hai mai soggiornato in un enorme unicorno di mare? No, non l'hai fatto, ma ora puoi barrarla dalla tua lista dei desideri. Questa magica opera d'arte fa parte di Willy Wonka, in parte Big Lebowski, e totalmente diversa da qualsiasi altra parte. Fallo per il grammo, ma anche per la tua anima.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 3,
    //         "beds" => 2,
    //         "bathrooms" => 1,
    //         "size" => 53,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 20,
    //         "user_id" => 2,
    //         "title" => "Quetzalcoatl",
    //         "street" => null,
    //         "description" => "Quetzalcoatl Nest è un complesso residenziale privato costruito dall'architetto Javier Senosiain, in cui segue gli aspetti dell'architettura organica, cercando di creare spazi più umani.",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 9,
    //         "beds" => 4,
    //         "bathrooms" => 4,
    //         "size" => 215,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
    //     [
    //         "id" => 21,
    //         "user_id" => 2,
    //         "title" => "Guitar House",
    //         "street" => null,
    //         "description" => "La nostra Guitar House è stata progettata per offrirti non solo un alloggio, ma anche un'esperienza completamente unica. Soggiornare nel nostro alloggio ti darà la sensazione di una minicasa, la vista di uno chalet di montagna, il comfort e lo spazio di un bungalow con acqua calda, riscaldamento, wifi ed elettricità. Qui sarai sulla griglia, ma fuori dal pavimento",
    //         "longitude" => null,
    //         "latitude" => null,
    //         "rooms" => 5,
    //         "beds" => 2,
    //         "bathrooms" => 1,
    //         "size" => 71,
    //         "visibility" => true,
    //         "cover" => "",
    //     ],
];