<?php

return [
    [
        "id" => 1,
        "apartment_id" => 1,
        "visit_date" => 11,
        "visitor_ip" => 2,
    ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],
    // [
    //     "id" => [],
    //     "apartment_id" => [],
    //     "visit_date" => [],
    //     "visitor_ip" => [],
    // ],    
];